name: 'EUserv Auto Extend'

on:
  workflow_dispatch:
  push:
    branches:
      - action

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@master

      - name: Install rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
          
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: ./target/release/euserv_extend
      
      - uses: actions/upload-artifact@v2
        with:
          name: euserv_extend
          path: ./target/release/euserv_extend
